import Link from "next/link";
import { ArrowRight, CalendarClock, CheckCircle2, CircleAlert, Link2, Sparkles } from "lucide-react";
import { PlatformIcon } from "@/components/ui/platform-icon";
import { StatusBadge } from "@/components/ui/status-badge";
import { publications } from "@/data/mock";

export default function DashboardPage() {
  const stats = [
    { title: "Agendadas", value: "4", note: "Próximos 7 dias", Icon: CalendarClock, color: "bg-amber-100 text-amber-700" },
    { title: "Publicadas", value: "18", note: "+12% este mês", Icon: CheckCircle2, color: "bg-emerald-100 text-emerald-700" },
    { title: "Conexões", value: "2", note: "de 6 disponíveis", Icon: Link2, color: "bg-blue-100 text-blue-700" },
    { title: "Atenção", value: "1", note: "conexão expirada", Icon: CircleAlert, color: "bg-red-100 text-red-700" },
  ];
  return <div className="space-y-8"><section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Sexta, 18 de setembro</p><h1 className="mt-3 text-3xl font-bold tracking-tight md:text-4xl">Bom dia, Marina.</h1><p className="mt-2 text-[#69736e]">Seu conteúdo está pronto para ganhar o mundo.</p></div><div className="rounded-full bg-[#e5eadf] px-4 py-2 text-xs font-semibold text-[#49624f]">● Ambiente de demonstração</div></section>
  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({ title, value, note, Icon, color }) => <article className="card lift p-5" key={title}><div className={`mb-6 flex h-9 w-9 items-center justify-center rounded-xl ${color}`}><Icon size={18}/></div><p className="text-3xl font-bold">{value}</p><div className="mt-1 flex items-center justify-between"><p className="text-sm font-semibold">{title}</p><p className="text-xs text-[#77817c]">{note}</p></div></article>)}</section>
  <section className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e5e5df] p-5 md:px-6"><div><h2 className="font-bold">Próximas publicações</h2><p className="mt-1 text-sm text-[#78817c]">Acompanhe o que vem por aí.</p></div><Link className="text-sm font-semibold text-[#426b54]" href="/calendario">Ver calendário</Link></div><div className="divide-y divide-[#e8e8e2]">{publications.slice(0,2).map(pub => <Link href={`/historico#${pub.id}`} className="flex items-center gap-4 p-5 hover:bg-white" key={pub.id}><div className="flex h-14 w-14 items-center justify-center rounded-xl bg-[#e2ddd0] text-xl">{pub.mediaType === "video" ? "▶" : "✦"}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{pub.baseText}</p><p className="mt-1 text-xs text-[#7b847f]">{pub.scheduledAt ? "Hoje · 18:30" : "15 set · 14:00"}</p></div><div className="hidden items-center sm:flex">{pub.destinations.map(d => <PlatformIcon key={d.id} platform={d.platform} small />)}</div><StatusBadge status={pub.status}/></Link>)}</div></div><div className="card relative overflow-hidden bg-[#315d43] p-6 text-white"><Sparkles className="absolute -right-4 -top-4 text-white/10" size={120}/><p className="eyebrow !text-[#bdd1c2]">Comece por aqui</p><h2 className="mt-4 max-w-xs text-2xl font-bold leading-tight">Uma ideia. Várias redes. Menos trabalho.</h2><p className="mt-3 max-w-sm text-sm leading-6 text-[#d6e3d9]">Crie seu conteúdo-base e personalize cada versão antes de publicar.</p><Link href="/publicacoes/nova" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-[#294d37]">Criar publicação <ArrowRight size={16}/></Link></div></section></div>;
}
