"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BarChart3, CalendarDays, ChevronDown, History, Link2, Menu, PenLine, X } from "lucide-react";
import { useState } from "react";
import { workspace } from "@/data/mock";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

const nav = [{ href: "/dashboard", label: "Visão geral", icon: BarChart3 }, { href: "/publicacoes/nova", label: "Nova publicação", icon: PenLine }, { href: "/calendario", label: "Calendário", icon: CalendarDays }, { href: "/historico", label: "Histórico", icon: History }, { href: "/conexoes", label: "Conexões", icon: Link2 }];
export function AppShell({ children }: { children: React.ReactNode }) {
  const path = usePathname(); const [open, setOpen] = useState(false);
  async function logout() { await createSupabaseBrowserClient()?.auth.signOut(); window.location.href = "/login"; }
  const sidebar = <><div className="flex h-20 items-center justify-between px-6"><Link href="/dashboard" className="text-2xl font-black tracking-[-.08em]">te<span className="text-[#6d957b]">l</span>a.</Link><button onClick={() => setOpen(false)} className="md:hidden" aria-label="Fechar menu"><X /></button></div><div className="mx-4 mb-6 rounded-xl border border-white/10 bg-white/5 p-3"><span className="eyebrow !text-[#9eaaa3]">Workspace</span><button className="mt-2 flex w-full items-center gap-3 text-left"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#d8e4da] text-xs font-bold text-[#294b37]">{workspace.initials}</span><span className="flex-1 truncate text-sm font-semibold text-white">{workspace.name}</span><ChevronDown size={14}/></button></div><nav className="space-y-1 px-3" aria-label="Principal">{nav.map(({ href, label, icon: Icon }) => { const active = path === href; return <Link onClick={() => setOpen(false)} key={href} href={href} className={`focusable flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${active ? "bg-[#dbe8dd] text-[#193526]" : "text-[#b8c2bc] hover:bg-white/5 hover:text-white"}`}><Icon size={18}/>{label}</Link>; })}</nav><div className="absolute bottom-0 left-0 right-0 border-t border-white/10 p-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#e8cfa8] text-xs font-bold text-[#47341b]">MA</span><div className="flex-1"><p className="text-sm font-semibold text-white">Marina Alves</p><button onClick={logout} className="text-xs text-[#929e97] hover:text-white">Sair da demonstração</button></div></div></div></>;
  return <div className="min-h-screen md:pl-64"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 bg-[#17231d] text-white md:block">{sidebar}</aside>{open && <div className="fixed inset-0 z-50 md:hidden"><button aria-label="Fechar menu" className="absolute inset-0 bg-black/35" onClick={() => setOpen(false)}/><aside className="relative h-full w-72 bg-[#17231d] text-white">{sidebar}</aside></div>}<header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-[#dedfd7] bg-[#f5f5ef]/90 px-5 backdrop-blur md:px-8"><button onClick={() => setOpen(true)} className="md:hidden" aria-label="Abrir menu"><Menu /></button><p className="hidden text-sm text-[#737d77] md:block">Tudo em um só lugar, no seu ritmo.</p><Link href="/publicacoes/nova" className="focusable rounded-xl bg-[#315d43] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#244b35]">+ Criar publicação</Link></header><main className="mx-auto max-w-[1440px] p-5 md:p-8 lg:p-10">{children}</main></div>;
}
