"use client";
import { useState } from "react";
import { Filter } from "lucide-react";
import { publications } from "@/data/mock";
import { platformLabels, socialPlatforms } from "@/domain/social";
import { publicationStatuses } from "@/domain/publication";
import { PlatformIcon } from "@/components/ui/platform-icon";
import { StatusBadge } from "@/components/ui/status-badge";
export default function HistoryPage() { const [network,setNetwork] = useState("all"); const [status,setStatus] = useState("all"); const filtered = publications.filter(p => (status === "all" || p.status === status) && (network === "all" || p.destinations.some(d => d.platform === network))); return <div className="space-y-7"><div><p className="eyebrow">Biblioteca</p><h1 className="mt-3 text-3xl font-bold tracking-tight">Histórico</h1><p className="mt-2 text-[#6d7772]">Acompanhe cada envio e o resultado por destino.</p></div><div className="card flex flex-col gap-3 p-4 sm:flex-row"><div className="flex items-center gap-2 text-sm font-bold"><Filter size={16}/> Filtrar</div><select aria-label="Filtrar por rede" value={network} onChange={e=>setNetwork(e.target.value)} className="rounded-lg border border-[#dadbd5] bg-white px-3 py-2 text-sm"><option value="all">Todas as redes</option>{socialPlatforms.map(p=><option key={p} value={p}>{platformLabels[p]}</option>)}</select><select aria-label="Filtrar por status" value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border border-[#dadbd5] bg-white px-3 py-2 text-sm"><option value="all">Todos os status</option>{publicationStatuses.map(s=><option key={s} value={s}>{s}</option>)}</select></div><div className="space-y-4">{filtered.map(p=><article id={p.id} className="card overflow-hidden" key={p.id}><div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-xl bg-[#e2ddd0] text-xl">{p.mediaType === "video" ? "▶" : "✦"}</div><div className="min-w-0 flex-1"><p className="font-bold">{p.baseText}</p><p className="mt-1 text-xs text-[#7b847f]">Criada em {new Date(p.createdAt).toLocaleDateString("pt-BR")} · {p.destinations.length} destinos</p></div><StatusBadge status={p.status}/></div><div className="border-t border-[#e5e5df] bg-[#fafaf7] px-5 py-3"><p className="eyebrow mb-3">Resultado por destino</p><div className="grid gap-2 md:grid-cols-2">{p.destinations.map(d=><div className="flex items-center gap-3 rounded-xl border border-[#e1e2dc] bg-white p-3" key={d.id}><PlatformIcon platform={d.platform} small/><div className="min-w-0 flex-1"><p className="text-xs font-bold">{platformLabels[d.platform]}</p><p className="truncate text-[11px] text-[#7d8580]">{d.lastError ?? `${d.attempts} tentativa${d.attempts === 1 ? "" : "s"}`}</p></div><StatusBadge status={d.status}/></div>)}</div></div></article>)}{!filtered.length && <div className="card p-10 text-center text-sm text-[#737d77]">Nenhuma publicação corresponde aos filtros.</div>}</div></div>; }
